// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/lib/js/src/jest.js");
var Colors_Support = require("../src/Colors_Support.js");

describe("colors.re Colors_Support", (function () {
        return Jest.test("isColorCompatibleCi returns 1 if TRAVIS CI", (function () {
                      (( process.env={"CI":"TRAVIS"}));
                      (( console.log(process.env)));
                      return Jest.ExpectJs[/* toBe */2](1, Jest.ExpectJs[/* expect */0](Colors_Support.isColorCompatibleCi(/* () */0)));
                    }));
      }));

/*  Not a pure module */
