// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/lib/js/src/jest.js");
var Colors_Support = require("../src/Colors_Support.js");

describe("colors.re Colors_Support", (function () {
        Jest.test("supportsColors", (function () {
                return Jest.ExpectJs[/* toBe */2](3, Jest.ExpectJs[/* expect */0](Colors_Support.supportsColors(/* :: */[
                                    1,
                                    /* :: */[
                                      2,
                                      /* :: */[
                                        3,
                                        /* [] */0
                                      ]
                                    ]
                                  ])));
              }));
        Jest.test("notFoundString", (function () {
                return Jest.ExpectJs[/* toBe */2]("NOT_FOUND", Jest.ExpectJs[/* expect */0](Colors_Support.notFoundStr));
              }));
        return Jest.test("safeGetEnv", (function () {
                      return Jest.ExpectJs[/* toBe */2]("NOT_FOUND", Jest.ExpectJs[/* expect */0](Colors_Support.safeGetEnv("SOME_RUBBISH_ENV")));
                    }));
      }));

/*  Not a pure module */
