// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/lib/js/src/jest.js");
var Colors = require("../src/Colors.js");

describe("colors.re", (function () {
        Jest.test("colors should not modify by default", (function () {
                return Jest.ExpectJs[/* toBe */2]("start", Jest.ExpectJs[/* expect */0](Colors.colors(/* None */0, /* None */0, /* None */0, /* None */0, "start")));
              }));
        Jest.test("colors should apply modifiers", (function () {
                return Jest.ExpectJs[/* toBe */2](( '\u001b[1m' + 'start' + '\u001b[22m' ), Jest.ExpectJs[/* expect */0](Colors.colors(/* None */0, /* None */0, /* Some */[/* Bold */1], /* None */0, "start")));
              }));
        Jest.test("colors should apply colors", (function () {
                return Jest.ExpectJs[/* toBe */2](( '\u001b[31m' + 'start' + '\u001b[39m' ), Jest.ExpectJs[/* expect */0](Colors.colors(/* Some */[/* Red */0], /* None */0, /* None */0, /* None */0, "start")));
              }));
        Jest.test("colors should apply backgrounds", (function () {
                return Jest.ExpectJs[/* toBe */2](( '\u001b[41m' + 'start' + '\u001b[49m' ), Jest.ExpectJs[/* expect */0](Colors.colors(/* None */0, /* Some */[/* BgRed */8], /* None */0, /* None */0, "start")));
              }));
        Jest.test("colors should hightlight keyword", (function () {
                return Jest.ExpectJs[/* toBe */2](( 'Hello ' + '\u001b[32m' + 'World' + '\u001b[39m' ), Jest.ExpectJs[/* expect */0](Colors.colors(/* None */0, /* None */0, /* None */0, /* Some */[/* record */[
                                      /* colorType : Green */2,
                                      /* word */"World"
                                    ]], "Hello World")));
              }));
        return Jest.test("colors should apply multiple changes to a string", (function () {
                      return Jest.ExpectJs[/* toBe */2](( '\u001b[41m' + '\u001b[34m' + 'start' + '\u001b[39m' + '\u001b[49m' ), Jest.ExpectJs[/* expect */0](Colors.colors(/* Some */[/* Blue */3], /* Some */[/* BgRed */8], /* None */0, /* None */0, "start")));
                    }));
      }));

/*  Not a pure module */
