// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';


var bgC = "49";

var colorC = "39";

var black_001 = /* :: */[
  colorC,
  /* [] */0
];

var black = /* :: */[
  "30",
  black_001
];

var red_001 = /* :: */[
  colorC,
  /* [] */0
];

var red = /* :: */[
  "31",
  red_001
];

var green_001 = /* :: */[
  colorC,
  /* [] */0
];

var green = /* :: */[
  "32",
  green_001
];

var yellow_001 = /* :: */[
  colorC,
  /* [] */0
];

var yellow = /* :: */[
  "33",
  yellow_001
];

var blue_001 = /* :: */[
  colorC,
  /* [] */0
];

var blue = /* :: */[
  "34",
  blue_001
];

var magenta_001 = /* :: */[
  colorC,
  /* [] */0
];

var magenta = /* :: */[
  "35",
  magenta_001
];

var cyan_001 = /* :: */[
  colorC,
  /* [] */0
];

var cyan = /* :: */[
  "36",
  cyan_001
];

var white_001 = /* :: */[
  colorC,
  /* [] */0
];

var white = /* :: */[
  "37",
  white_001
];

var gray_001 = /* :: */[
  colorC,
  /* [] */0
];

var gray = /* :: */[
  "90",
  gray_001
];

var grey_001 = /* :: */[
  colorC,
  /* [] */0
];

var grey = /* :: */[
  "90",
  grey_001
];

var bgBlack_001 = /* :: */[
  bgC,
  /* [] */0
];

var bgBlack = /* :: */[
  "40",
  bgBlack_001
];

var bgRed_001 = /* :: */[
  bgC,
  /* [] */0
];

var bgRed = /* :: */[
  "41",
  bgRed_001
];

var bgGreen_001 = /* :: */[
  bgC,
  /* [] */0
];

var bgGreen = /* :: */[
  "42",
  bgGreen_001
];

var bgYellow_001 = /* :: */[
  bgC,
  /* [] */0
];

var bgYellow = /* :: */[
  "43",
  bgYellow_001
];

var bgBlue_001 = /* :: */[
  bgC,
  /* [] */0
];

var bgBlue = /* :: */[
  "44",
  bgBlue_001
];

var bgMagenta_001 = /* :: */[
  bgC,
  /* [] */0
];

var bgMagenta = /* :: */[
  "45",
  bgMagenta_001
];

var bgCyan_001 = /* :: */[
  bgC,
  /* [] */0
];

var bgCyan = /* :: */[
  "46",
  bgCyan_001
];

var bgWhite_001 = /* :: */[
  bgC,
  /* [] */0
];

var bgWhite = /* :: */[
  "47",
  bgWhite_001
];

var bgBlackBright_001 = /* :: */[
  bgC,
  /* [] */0
];

var bgBlackBright = /* :: */[
  "100",
  bgBlackBright_001
];

var bgRedBright_001 = /* :: */[
  bgC,
  /* [] */0
];

var bgRedBright = /* :: */[
  "101",
  bgRedBright_001
];

var bgGreenBright_001 = /* :: */[
  bgC,
  /* [] */0
];

var bgGreenBright = /* :: */[
  "102",
  bgGreenBright_001
];

var bgYellowBright_001 = /* :: */[
  bgC,
  /* [] */0
];

var bgYellowBright = /* :: */[
  "103",
  bgYellowBright_001
];

var bgBlueBright_001 = /* :: */[
  bgC,
  /* [] */0
];

var bgBlueBright = /* :: */[
  "104",
  bgBlueBright_001
];

var bgMagentaBright_001 = /* :: */[
  bgC,
  /* [] */0
];

var bgMagentaBright = /* :: */[
  "105",
  bgMagentaBright_001
];

var bgCyanBright_001 = /* :: */[
  bgC,
  /* [] */0
];

var bgCyanBright = /* :: */[
  "106",
  bgCyanBright_001
];

var bgWhiteBright_001 = /* :: */[
  bgC,
  /* [] */0
];

var bgWhiteBright = /* :: */[
  "107",
  bgWhiteBright_001
];

var Colors_Styles_002 = /* reset : :: */[
  "0",
  /* :: */[
    "0",
    /* [] */0
  ]
];

var Colors_Styles_003 = /* bold : :: */[
  "1",
  /* :: */[
    "22",
    /* [] */0
  ]
];

var Colors_Styles_004 = /* dim : :: */[
  "2",
  /* :: */[
    "22",
    /* [] */0
  ]
];

var Colors_Styles_005 = /* italic : :: */[
  "3",
  /* :: */[
    "23",
    /* [] */0
  ]
];

var Colors_Styles_006 = /* underline : :: */[
  "4",
  /* :: */[
    "24",
    /* [] */0
  ]
];

var Colors_Styles_007 = /* inverse : :: */[
  "7",
  /* :: */[
    "27",
    /* [] */0
  ]
];

var Colors_Styles_008 = /* hidden : :: */[
  "8",
  /* :: */[
    "28",
    /* [] */0
  ]
];

var Colors_Styles_009 = /* strikethrough : :: */[
  "9",
  /* :: */[
    "29",
    /* [] */0
  ]
];

var Colors_Styles = /* module */[
  /* bgC */bgC,
  /* colorC */colorC,
  Colors_Styles_002,
  Colors_Styles_003,
  Colors_Styles_004,
  Colors_Styles_005,
  Colors_Styles_006,
  Colors_Styles_007,
  Colors_Styles_008,
  Colors_Styles_009,
  /* black */black,
  /* red */red,
  /* green */green,
  /* yellow */yellow,
  /* blue */blue,
  /* magenta */magenta,
  /* cyan */cyan,
  /* white */white,
  /* gray */gray,
  /* grey */grey,
  /* bgBlack */bgBlack,
  /* bgRed */bgRed,
  /* bgGreen */bgGreen,
  /* bgYellow */bgYellow,
  /* bgBlue */bgBlue,
  /* bgMagenta */bgMagenta,
  /* bgCyan */bgCyan,
  /* bgWhite */bgWhite,
  /* bgBlackBright */bgBlackBright,
  /* bgRedBright */bgRedBright,
  /* bgGreenBright */bgGreenBright,
  /* bgYellowBright */bgYellowBright,
  /* bgBlueBright */bgBlueBright,
  /* bgMagentaBright */bgMagentaBright,
  /* bgCyanBright */bgCyanBright,
  /* bgWhiteBright */bgWhiteBright
];

exports.Colors_Styles = Colors_Styles;
/* No side effect */
