// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Printf = require("bs-platform/lib/js/printf.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function convertToHexidecimal(num) {
  var convert = Curry._1(Printf.sprintf(/* Format */[
            /* Int */Block.__(4, [
                /* Int_x */6,
                /* No_padding */0,
                /* No_precision */0,
                /* End_of_format */0
              ]),
            "%x"
          ]), num);
  var match = +(convert.length === 1);
  if (match !== 0) {
    return "0" + convert;
  } else {
    return convert;
  }
}

function hex(rgb) {
  var exit = 0;
  if (rgb) {
    var match = rgb[1];
    if (match) {
      var match$1 = match[1];
      if (match$1) {
        if (match$1[1]) {
          exit = 1;
        } else {
          return "#" + (convertToHexidecimal(rgb[0]) + (convertToHexidecimal(match[0]) + convertToHexidecimal(match$1[0])));
        }
      } else {
        exit = 1;
      }
    } else {
      exit = 1;
    }
  } else {
    exit = 1;
  }
  if (exit === 1) {
    throw [
          Caml_builtin_exceptions.match_failure,
          [
            "Colors_Convert.re",
            9,
            10
          ]
        ];
  }
  
}

var RGB = /* module */[/* hex */hex];

var Convert = /* module */[/* RGB */RGB];

var convertTest = hex(/* :: */[
      92,
      /* :: */[
        191,
        /* :: */[
          84,
          /* [] */0
        ]
      ]
    ]);

console.log(convertTest);

exports.convertToHexidecimal = convertToHexidecimal;
exports.Convert = Convert;
exports.convertTest = convertTest;
/* convertTest Not a pure module */
