// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';


var Colors_Styles_000 = /* reset : :: */[
  "0",
  /* :: */[
    "0",
    /* [] */0
  ]
];

var Colors_Styles_001 = /* bold : :: */[
  "1",
  /* :: */[
    "22",
    /* [] */0
  ]
];

var Colors_Styles_002 = /* dim : :: */[
  "2",
  /* :: */[
    "22",
    /* [] */0
  ]
];

var Colors_Styles_003 = /* italic : :: */[
  "3",
  /* :: */[
    "23",
    /* [] */0
  ]
];

var Colors_Styles_004 = /* underline : :: */[
  "4",
  /* :: */[
    "24",
    /* [] */0
  ]
];

var Colors_Styles_005 = /* inverse : :: */[
  "7",
  /* :: */[
    "27",
    /* [] */0
  ]
];

var Colors_Styles_006 = /* hidden : :: */[
  "8",
  /* :: */[
    "28",
    /* [] */0
  ]
];

var Colors_Styles_007 = /* strikethrough : :: */[
  "9",
  /* :: */[
    "29",
    /* [] */0
  ]
];

var Colors_Styles_008 = /* black : :: */[
  "30",
  /* :: */[
    "39",
    /* [] */0
  ]
];

var Colors_Styles_009 = /* red : :: */[
  "31",
  /* :: */[
    "39",
    /* [] */0
  ]
];

var Colors_Styles_010 = /* green : :: */[
  "32",
  /* :: */[
    "39",
    /* [] */0
  ]
];

var Colors_Styles_011 = /* yellow : :: */[
  "33",
  /* :: */[
    "39",
    /* [] */0
  ]
];

var Colors_Styles_012 = /* blue : :: */[
  "34",
  /* :: */[
    "39",
    /* [] */0
  ]
];

var Colors_Styles_013 = /* magenta : :: */[
  "35",
  /* :: */[
    "39",
    /* [] */0
  ]
];

var Colors_Styles_014 = /* cyan : :: */[
  "36",
  /* :: */[
    "39",
    /* [] */0
  ]
];

var Colors_Styles_015 = /* white : :: */[
  "37",
  /* :: */[
    "39",
    /* [] */0
  ]
];

var Colors_Styles_016 = /* gray : :: */[
  "90",
  /* :: */[
    "39",
    /* [] */0
  ]
];

var Colors_Styles_017 = /* grey : :: */[
  "90",
  /* :: */[
    "39",
    /* [] */0
  ]
];

var Colors_Styles_018 = /* bgBlack : :: */[
  "40",
  /* :: */[
    "49",
    /* [] */0
  ]
];

var Colors_Styles_019 = /* bgRed : :: */[
  "41",
  /* :: */[
    "49",
    /* [] */0
  ]
];

var Colors_Styles_020 = /* bgGreen : :: */[
  "42",
  /* :: */[
    "49",
    /* [] */0
  ]
];

var Colors_Styles_021 = /* bgYellow : :: */[
  "43",
  /* :: */[
    "49",
    /* [] */0
  ]
];

var Colors_Styles_022 = /* bgBlue : :: */[
  "44",
  /* :: */[
    "49",
    /* [] */0
  ]
];

var Colors_Styles_023 = /* bgMagenta : :: */[
  "45",
  /* :: */[
    "49",
    /* [] */0
  ]
];

var Colors_Styles_024 = /* bgCyan : :: */[
  "46",
  /* :: */[
    "49",
    /* [] */0
  ]
];

var Colors_Styles_025 = /* bgWhite : :: */[
  "47",
  /* :: */[
    "49",
    /* [] */0
  ]
];

var Colors_Styles_026 = /* bgBlackBright : :: */[
  "100",
  /* :: */[
    "49",
    /* [] */0
  ]
];

var Colors_Styles_027 = /* bgRedBright : :: */[
  "101",
  /* :: */[
    "49",
    /* [] */0
  ]
];

var Colors_Styles_028 = /* bgGreenBright : :: */[
  "102",
  /* :: */[
    "49",
    /* [] */0
  ]
];

var Colors_Styles_029 = /* bgYellowBright : :: */[
  "103",
  /* :: */[
    "49",
    /* [] */0
  ]
];

var Colors_Styles_030 = /* bgBlueBright : :: */[
  "104",
  /* :: */[
    "49",
    /* [] */0
  ]
];

var Colors_Styles_031 = /* bgMagentaBright : :: */[
  "105",
  /* :: */[
    "49",
    /* [] */0
  ]
];

var Colors_Styles_032 = /* bgCyanBright : :: */[
  "106",
  /* :: */[
    "49",
    /* [] */0
  ]
];

var Colors_Styles_033 = /* bgWhiteBright : :: */[
  "107",
  /* :: */[
    "49",
    /* [] */0
  ]
];

var Colors_Styles = /* module */[
  Colors_Styles_000,
  Colors_Styles_001,
  Colors_Styles_002,
  Colors_Styles_003,
  Colors_Styles_004,
  Colors_Styles_005,
  Colors_Styles_006,
  Colors_Styles_007,
  Colors_Styles_008,
  Colors_Styles_009,
  Colors_Styles_010,
  Colors_Styles_011,
  Colors_Styles_012,
  Colors_Styles_013,
  Colors_Styles_014,
  Colors_Styles_015,
  Colors_Styles_016,
  Colors_Styles_017,
  Colors_Styles_018,
  Colors_Styles_019,
  Colors_Styles_020,
  Colors_Styles_021,
  Colors_Styles_022,
  Colors_Styles_023,
  Colors_Styles_024,
  Colors_Styles_025,
  Colors_Styles_026,
  Colors_Styles_027,
  Colors_Styles_028,
  Colors_Styles_029,
  Colors_Styles_030,
  Colors_Styles_031,
  Colors_Styles_032,
  Colors_Styles_033
];

exports.Colors_Styles = Colors_Styles;
/* No side effect */
