// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Colors_Utils = require("./Colors_Utils.js");

function changeColor(c, str) {
  switch (c) {
    case 0 : 
        return Curry._1(Colors_Utils.Colors_Utils[/* red */11], str);
    case 1 : 
        return Curry._1(Colors_Utils.Colors_Utils[/* yellow */13], str);
    case 2 : 
        return Curry._1(Colors_Utils.Colors_Utils[/* green */12], str);
    case 3 : 
        return Curry._1(Colors_Utils.Colors_Utils[/* blue */14], str);
    case 4 : 
        return Curry._1(Colors_Utils.Colors_Utils[/* white */17], str);
    case 5 : 
        return Curry._1(Colors_Utils.Colors_Utils[/* cyan */16], str);
    case 6 : 
        return Curry._1(Colors_Utils.Colors_Utils[/* magenta */15], str);
    case 7 : 
        return Curry._1(Colors_Utils.Colors_Utils[/* bgBlack */20], str);
    case 8 : 
        return Curry._1(Colors_Utils.Colors_Utils[/* bgRed */21], str);
    case 9 : 
        return Curry._1(Colors_Utils.Colors_Utils[/* bgGreen */22], str);
    case 10 : 
        return Curry._1(Colors_Utils.Colors_Utils[/* bgYellow */23], str);
    case 11 : 
        return Curry._1(Colors_Utils.Colors_Utils[/* bgBlue */24], str);
    case 12 : 
        return Curry._1(Colors_Utils.Colors_Utils[/* bgMagenta */25], str);
    case 13 : 
        return Curry._1(Colors_Utils.Colors_Utils[/* bgCyan */26], str);
    case 14 : 
        return Curry._1(Colors_Utils.Colors_Utils[/* bgWhite */27], str);
    case 15 : 
        return Curry._1(Colors_Utils.Colors_Utils[/* bgRedBright */29], str);
    case 16 : 
        return Curry._1(Colors_Utils.Colors_Utils[/* bgGreenBright */30], str);
    case 17 : 
        return Curry._1(Colors_Utils.Colors_Utils[/* bgYellowBright */31], str);
    case 18 : 
        return Curry._1(Colors_Utils.Colors_Utils[/* bgBlueBright */32], str);
    case 19 : 
        return Curry._1(Colors_Utils.Colors_Utils[/* bgMagentaBright */33], str);
    case 20 : 
        return Curry._1(Colors_Utils.Colors_Utils[/* bgCyanBright */34], str);
    case 21 : 
        return Curry._1(Colors_Utils.Colors_Utils[/* bgWhiteBright */35], str);
    
  }
}

function modify(m, str) {
  switch (m) {
    case 0 : 
        return Curry._1(Colors_Utils.Colors_Utils[/* reset */2], str);
    case 1 : 
        return Curry._1(Colors_Utils.Colors_Utils[/* bold */3], str);
    case 2 : 
        return Curry._1(Colors_Utils.Colors_Utils[/* dim */4], str);
    case 3 : 
        return Curry._1(Colors_Utils.Colors_Utils[/* italic */5], str);
    case 4 : 
        return Curry._1(Colors_Utils.Colors_Utils[/* underline */6], str);
    case 5 : 
        return Curry._1(Colors_Utils.Colors_Utils[/* inverse */7], str);
    case 6 : 
        return Curry._1(Colors_Utils.Colors_Utils[/* hidden */8], str);
    case 7 : 
        return Curry._1(Colors_Utils.Colors_Utils[/* strikethrough */9], str);
    
  }
}

function changeKeyword(keyword, str, color) {
  var containsString = +str.includes(keyword);
  if (containsString !== 0) {
    return str.replace(keyword, changeColor(color, keyword));
  } else {
    return str;
  }
}

function doColorChange(color, keywordOptions, str) {
  if (color) {
    var c = color[0];
    if (keywordOptions) {
      var word = keywordOptions[0][/* word */1];
      return str.split(" ").map((function (x) {
                      var match = +(x === word);
                      if (match !== 0) {
                        return x;
                      } else {
                        return changeColor(c, x);
                      }
                    })).join(" ");
    } else {
      return changeColor(c, str);
    }
  } else {
    return str;
  }
}

function doModifier(modifier, str) {
  if (modifier) {
    return modify(modifier[0], str);
  } else {
    return str;
  }
}

function highlightKeyword(options, str) {
  if (options) {
    var match = options[0];
    return changeKeyword(match[/* word */1], str, match[/* colorType */0]);
  } else {
    return str;
  }
}

function changeBackground(c, str) {
  switch (c) {
    case 7 : 
        return Curry._1(Colors_Utils.Colors_Utils[/* bgBlack */20], str);
    case 0 : 
    case 8 : 
        return Curry._1(Colors_Utils.Colors_Utils[/* bgRed */21], str);
    case 2 : 
    case 9 : 
        return Curry._1(Colors_Utils.Colors_Utils[/* bgGreen */22], str);
    case 1 : 
    case 10 : 
        return Curry._1(Colors_Utils.Colors_Utils[/* bgYellow */23], str);
    case 3 : 
    case 11 : 
        return Curry._1(Colors_Utils.Colors_Utils[/* bgBlue */24], str);
    case 6 : 
    case 12 : 
        return Curry._1(Colors_Utils.Colors_Utils[/* bgMagenta */25], str);
    case 5 : 
    case 13 : 
        return Curry._1(Colors_Utils.Colors_Utils[/* bgCyan */26], str);
    case 4 : 
    case 14 : 
        return Curry._1(Colors_Utils.Colors_Utils[/* bgWhite */27], str);
    case 15 : 
        return Curry._1(Colors_Utils.Colors_Utils[/* bgRedBright */29], str);
    case 16 : 
        return Curry._1(Colors_Utils.Colors_Utils[/* bgGreenBright */30], str);
    case 17 : 
        return Curry._1(Colors_Utils.Colors_Utils[/* bgYellowBright */31], str);
    case 18 : 
        return Curry._1(Colors_Utils.Colors_Utils[/* bgBlueBright */32], str);
    case 19 : 
        return Curry._1(Colors_Utils.Colors_Utils[/* bgMagentaBright */33], str);
    case 20 : 
        return Curry._1(Colors_Utils.Colors_Utils[/* bgCyanBright */34], str);
    case 21 : 
        return Curry._1(Colors_Utils.Colors_Utils[/* bgWhiteBright */35], str);
    
  }
}

function applyBackgroud(bg, str) {
  if (bg) {
    return changeBackground(bg[0], str);
  } else {
    return str;
  }
}

function colors(color, bg, modifier, keywordOptions, str) {
  return applyBackgroud(bg, doColorChange(color, keywordOptions, doModifier(modifier, highlightKeyword(keywordOptions, str))));
}

exports.changeColor = changeColor;
exports.modify = modify;
exports.changeKeyword = changeKeyword;
exports.doColorChange = doColorChange;
exports.doModifier = doModifier;
exports.highlightKeyword = highlightKeyword;
exports.changeBackground = changeBackground;
exports.applyBackgroud = applyBackgroud;
exports.colors = colors;
/* Colors_Utils Not a pure module */
