// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Utils = require("./Utils.js");

function changeColor(c, str) {
  switch (c) {
    case 0 : 
        return Utils.Utils[/* red */11](str);
    case 1 : 
        return Utils.Utils[/* yellow */13](str);
    case 2 : 
        return Utils.Utils[/* green */12](str);
    case 3 : 
        return Utils.Utils[/* blue */14](str);
    case 4 : 
        return Utils.Utils[/* white */17](str);
    case 5 : 
        return Utils.Utils[/* cyan */16](str);
    case 6 : 
        return Utils.Utils[/* magenta */15](str);
    
  }
}

function modify(m, str) {
  switch (m) {
    case 0 : 
        return Utils.Utils[/* reset */2](str);
    case 1 : 
        return Utils.Utils[/* bold */3](str);
    case 2 : 
        return Utils.Utils[/* dim */4](str);
    case 3 : 
        return Utils.Utils[/* italic */5](str);
    case 4 : 
        return Utils.Utils[/* underline */6](str);
    case 5 : 
        return Utils.Utils[/* inverse */7](str);
    case 6 : 
        return Utils.Utils[/* hidden */8](str);
    case 7 : 
        return Utils.Utils[/* strikethrough */9](str);
    
  }
}

function changeKeyword(keyword, str, color) {
  var containsString = +str.includes(keyword);
  if (containsString !== 0) {
    return str.replace(keyword, changeColor(color, keyword));
  } else {
    return str;
  }
}

function changeColor$1(color, keywordOptions, str) {
  if (color) {
    var c = color[0];
    if (keywordOptions) {
      var word = keywordOptions[0][/* word */1];
      return str.split(" ").map((function (x) {
                      var match = +(x === word);
                      if (match !== 0) {
                        return x;
                      } else {
                        return changeColor(c, x);
                      }
                    })).join(" ");
    } else {
      return changeColor(c, str);
    }
  } else {
    return str;
  }
}

function doModifier(modifier, str) {
  if (modifier) {
    return modify(modifier[0], str);
  } else {
    return str;
  }
}

function highlightKeyword(options, str) {
  if (options) {
    var match = options[0];
    return changeKeyword(match[/* word */1], str, match[/* colorType */0]);
  } else {
    return str;
  }
}

function changeBackground(c, str) {
  switch (c) {
    case 0 : 
        return Utils.Utils[/* bgRed */21](str);
    case 1 : 
        return Utils.Utils[/* bgYellow */23](str);
    case 2 : 
        return Utils.Utils[/* bgGreen */22](str);
    case 3 : 
        return Utils.Utils[/* bgBlue */24](str);
    case 4 : 
        return Utils.Utils[/* bgWhite */27](str);
    case 5 : 
        return Utils.Utils[/* bgCyan */26](str);
    case 6 : 
        return Utils.Utils[/* bgMagenta */25](str);
    
  }
}

function applyBackgroud(bg, str) {
  if (bg) {
    return changeBackground(bg[0], str);
  } else {
    return str;
  }
}

function recolor(color, bg, modifier, keywordOptions, str) {
  return applyBackgroud(bg, changeColor$1(color, keywordOptions, doModifier(modifier, highlightKeyword(keywordOptions, str))));
}

var myString = recolor(/* Some */[/* Yellow */1], /* Some */[/* Blue */3], /* Some */[/* Bold */1], /* Some */[/* record */[
        /* colorType : Green */2,
        /* word */"my"
      ]], "this is my string");

console.log(myString);

exports.modify           = modify;
exports.changeKeyword    = changeKeyword;
exports.changeColor      = changeColor$1;
exports.doModifier       = doModifier;
exports.highlightKeyword = highlightKeyword;
exports.changeBackground = changeBackground;
exports.applyBackgroud   = applyBackgroud;
exports.recolor          = recolor;
exports.myString         = myString;
/* myString Not a pure module */
