// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry      = require("bs-platform/lib/js/curry.js");
var Styles     = require("./Styles.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");

function startWrap(v) {
  return "\u001b[" + (String(v) + "") + "m";
}

function endWrap(v) {
  return "\u001b[" + (String(v) + "") + "m";
}

function compose(f, g, x) {
  return Curry._1(f, Curry._1(g, x));
}

function pipe(f, g, x) {
  return Curry._1(g, Curry._1(f, x));
}

function reset(str) {
  return startWrap(Caml_array.caml_array_get(Styles.Styles[/* reset */0], 0)) + (str + endWrap(Caml_array.caml_array_get(Styles.Styles[/* reset */0], 1)));
}

function bold(str) {
  return startWrap(Caml_array.caml_array_get(Styles.Styles[/* bold */1], 0)) + (str + endWrap(Caml_array.caml_array_get(Styles.Styles[/* bold */1], 1)));
}

function dim(str) {
  return startWrap(Caml_array.caml_array_get(Styles.Styles[/* dim */2], 0)) + (str + endWrap(Caml_array.caml_array_get(Styles.Styles[/* dim */2], 1)));
}

function italic(str) {
  return startWrap(Caml_array.caml_array_get(Styles.Styles[/* italic */3], 0)) + (str + endWrap(Caml_array.caml_array_get(Styles.Styles[/* italic */3], 1)));
}

function underline(str) {
  return startWrap(Caml_array.caml_array_get(Styles.Styles[/* underline */4], 0)) + (str + endWrap(Caml_array.caml_array_get(Styles.Styles[/* underline */4], 1)));
}

function inverse(str) {
  return startWrap(Caml_array.caml_array_get(Styles.Styles[/* inverse */5], 0)) + (str + endWrap(Caml_array.caml_array_get(Styles.Styles[/* inverse */5], 1)));
}

function hidden(str) {
  return startWrap(Caml_array.caml_array_get(Styles.Styles[/* hidden */6], 0)) + (str + endWrap(Caml_array.caml_array_get(Styles.Styles[/* hidden */6], 1)));
}

function strikethrough(str) {
  return startWrap(Caml_array.caml_array_get(Styles.Styles[/* strikethrough */7], 0)) + (str + endWrap(Caml_array.caml_array_get(Styles.Styles[/* strikethrough */7], 1)));
}

function black(str) {
  return startWrap(Caml_array.caml_array_get(Styles.Styles[/* black */8], 0)) + (str + endWrap(Caml_array.caml_array_get(Styles.Styles[/* black */8], 1)));
}

function red(str) {
  return startWrap(Caml_array.caml_array_get(Styles.Styles[/* red */9], 0)) + (str + endWrap(Caml_array.caml_array_get(Styles.Styles[/* red */9], 1)));
}

function green(str) {
  return startWrap(Caml_array.caml_array_get(Styles.Styles[/* green */10], 0)) + (str + endWrap(Caml_array.caml_array_get(Styles.Styles[/* green */10], 1)));
}

function yellow(str) {
  return startWrap(Caml_array.caml_array_get(Styles.Styles[/* yellow */11], 0)) + (str + endWrap(Caml_array.caml_array_get(Styles.Styles[/* yellow */11], 1)));
}

function blue(str) {
  return startWrap(Caml_array.caml_array_get(Styles.Styles[/* blue */12], 0)) + (str + endWrap(Caml_array.caml_array_get(Styles.Styles[/* blue */12], 1)));
}

function magenta(str) {
  return startWrap(Caml_array.caml_array_get(Styles.Styles[/* magenta */13], 0)) + (str + endWrap(Caml_array.caml_array_get(Styles.Styles[/* magenta */13], 1)));
}

function cyan(str) {
  return startWrap(Caml_array.caml_array_get(Styles.Styles[/* cyan */14], 0)) + (str + endWrap(Caml_array.caml_array_get(Styles.Styles[/* cyan */14], 1)));
}

function white(str) {
  return startWrap(Caml_array.caml_array_get(Styles.Styles[/* white */15], 0)) + (str + endWrap(Caml_array.caml_array_get(Styles.Styles[/* white */15], 1)));
}

function gray(str) {
  return startWrap(Caml_array.caml_array_get(Styles.Styles[/* gray */16], 0)) + (str + endWrap(Caml_array.caml_array_get(Styles.Styles[/* gray */16], 1)));
}

function grey(str) {
  return startWrap(Caml_array.caml_array_get(Styles.Styles[/* grey */17], 0)) + (str + endWrap(Caml_array.caml_array_get(Styles.Styles[/* grey */17], 1)));
}

function bgBlack(str) {
  return startWrap(Caml_array.caml_array_get(Styles.Styles[/* bgBlack */18], 0)) + (str + endWrap(Caml_array.caml_array_get(Styles.Styles[/* bgBlack */18], 1)));
}

function bgRed(str) {
  return startWrap(Caml_array.caml_array_get(Styles.Styles[/* bgRed */19], 0)) + (str + endWrap(Caml_array.caml_array_get(Styles.Styles[/* bgRed */19], 1)));
}

function bgGreen(str) {
  return startWrap(Caml_array.caml_array_get(Styles.Styles[/* bgGreen */20], 0)) + (str + endWrap(Caml_array.caml_array_get(Styles.Styles[/* bgGreen */20], 1)));
}

function bgYellow(str) {
  return startWrap(Caml_array.caml_array_get(Styles.Styles[/* bgYellow */21], 0)) + (str + endWrap(Caml_array.caml_array_get(Styles.Styles[/* bgYellow */21], 1)));
}

function bgBlue(str) {
  return startWrap(Caml_array.caml_array_get(Styles.Styles[/* bgBlue */22], 0)) + (str + endWrap(Caml_array.caml_array_get(Styles.Styles[/* bgBlue */22], 1)));
}

function bgMagenta(str) {
  return startWrap(Caml_array.caml_array_get(Styles.Styles[/* bgMagenta */23], 0)) + (str + endWrap(Caml_array.caml_array_get(Styles.Styles[/* bgMagenta */23], 1)));
}

function bgCyan(str) {
  return startWrap(Caml_array.caml_array_get(Styles.Styles[/* bgCyan */24], 0)) + (str + endWrap(Caml_array.caml_array_get(Styles.Styles[/* bgCyan */24], 1)));
}

function bgWhite(str) {
  return startWrap(Caml_array.caml_array_get(Styles.Styles[/* bgWhite */25], 0)) + (str + endWrap(Caml_array.caml_array_get(Styles.Styles[/* bgWhite */25], 1)));
}

var Recolor = /* module */[
  /* compose */compose,
  /* pipe */pipe,
  /* reset */reset,
  /* bold */bold,
  /* dim */dim,
  /* italic */italic,
  /* underline */underline,
  /* inverse */inverse,
  /* hidden */hidden,
  /* strikethrough */strikethrough,
  /* black */black,
  /* red */red,
  /* green */green,
  /* yellow */yellow,
  /* blue */blue,
  /* magenta */magenta,
  /* cyan */cyan,
  /* white */white,
  /* gray */gray,
  /* grey */grey,
  /* bgBlack */bgBlack,
  /* bgRed */bgRed,
  /* bgGreen */bgGreen,
  /* bgYellow */bgYellow,
  /* bgBlue */bgBlue,
  /* bgMagenta */bgMagenta,
  /* bgCyan */bgCyan,
  /* bgWhite */bgWhite
];

function changeColor(c, str) {
  switch (c) {
    case 0 : 
        return red(str);
    case 1 : 
        return yellow(str);
    case 2 : 
        return green(str);
    case 3 : 
        return blue(str);
    case 4 : 
        return white(str);
    case 5 : 
        return cyan(str);
    case 6 : 
        return magenta(str);
    
  }
}

function modify(m, str) {
  switch (m) {
    case 0 : 
        return reset(str);
    case 1 : 
        return bold(str);
    case 2 : 
        return dim(str);
    case 3 : 
        return italic(str);
    case 4 : 
        return underline(str);
    case 5 : 
        return inverse(str);
    case 6 : 
        return hidden(str);
    case 7 : 
        return strikethrough(str);
    
  }
}

function changeKeyword(keyword, str, color) {
  var containsString = +str.includes(keyword);
  if (containsString !== 0) {
    return str.split(" ").map((function (x) {
                    var match = +(x === keyword);
                    if (match !== 0) {
                      return changeColor(color, x);
                    } else {
                      return x;
                    }
                  })).join(" ");
  } else {
    return str;
  }
}

function recolor(color, modifier, keyword, str) {
  if (keyword) {
    return changeKeyword(keyword[0], str, /* Red */0);
  } else if (color) {
    var c = color[0];
    if (modifier) {
      return changeColor(c, modify(modifier[0], str));
    } else {
      return changeColor(c, str);
    }
  } else if (modifier) {
    return modify(modifier[0], str);
  } else {
    return str;
  }
}

var myString = recolor(/* Some */[/* Red */0], /* Some */[/* Underline */4], /* None */0, "this is my string");

var keyWordTest = recolor(/* None */0, /* None */0, /* Some */["Dog"], "Hello my Dog");

console.log(keyWordTest);

console.log(myString);

var myTester = changeKeyword("hello", "hello wold hello", /* Green */2);

console.log(myTester);

exports.startWrap     = startWrap;
exports.endWrap       = endWrap;
exports.Recolor       = Recolor;
exports.changeColor   = changeColor;
exports.modify        = modify;
exports.changeKeyword = changeKeyword;
exports.recolor       = recolor;
exports.myString      = myString;
exports.keyWordTest   = keyWordTest;
exports.myTester      = myTester;
/* myString Not a pure module */
