// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


var Styles_000 = /* reset : :: */[
  "0",
  /* :: */[
    "0",
    /* [] */0
  ]
];

var Styles_001 = /* bold : :: */[
  "1",
  /* :: */[
    "22",
    /* [] */0
  ]
];

var Styles_002 = /* dim : :: */[
  "2",
  /* :: */[
    "22",
    /* [] */0
  ]
];

var Styles_003 = /* italic : :: */[
  "3",
  /* :: */[
    "23",
    /* [] */0
  ]
];

var Styles_004 = /* underline : :: */[
  "4",
  /* :: */[
    "24",
    /* [] */0
  ]
];

var Styles_005 = /* inverse : :: */[
  "7",
  /* :: */[
    "27",
    /* [] */0
  ]
];

var Styles_006 = /* hidden : :: */[
  "8",
  /* :: */[
    "28",
    /* [] */0
  ]
];

var Styles_007 = /* strikethrough : :: */[
  "9",
  /* :: */[
    "29",
    /* [] */0
  ]
];

var Styles_008 = /* black : :: */[
  "30",
  /* :: */[
    "39",
    /* [] */0
  ]
];

var Styles_009 = /* red : :: */[
  "31",
  /* :: */[
    "39",
    /* [] */0
  ]
];

var Styles_010 = /* green : :: */[
  "32",
  /* :: */[
    "39",
    /* [] */0
  ]
];

var Styles_011 = /* yellow : :: */[
  "33",
  /* :: */[
    "39",
    /* [] */0
  ]
];

var Styles_012 = /* blue : :: */[
  "34",
  /* :: */[
    "39",
    /* [] */0
  ]
];

var Styles_013 = /* magenta : :: */[
  "35",
  /* :: */[
    "39",
    /* [] */0
  ]
];

var Styles_014 = /* cyan : :: */[
  "36",
  /* :: */[
    "39",
    /* [] */0
  ]
];

var Styles_015 = /* white : :: */[
  "37",
  /* :: */[
    "39",
    /* [] */0
  ]
];

var Styles_016 = /* gray : :: */[
  "90",
  /* :: */[
    "39",
    /* [] */0
  ]
];

var Styles_017 = /* grey : :: */[
  "90",
  /* :: */[
    "39",
    /* [] */0
  ]
];

var Styles_018 = /* bgBlack : :: */[
  "40",
  /* :: */[
    "49",
    /* [] */0
  ]
];

var Styles_019 = /* bgRed : :: */[
  "41",
  /* :: */[
    "49",
    /* [] */0
  ]
];

var Styles_020 = /* bgGreen : :: */[
  "42",
  /* :: */[
    "49",
    /* [] */0
  ]
];

var Styles_021 = /* bgYellow : :: */[
  "43",
  /* :: */[
    "49",
    /* [] */0
  ]
];

var Styles_022 = /* bgBlue : :: */[
  "44",
  /* :: */[
    "49",
    /* [] */0
  ]
];

var Styles_023 = /* bgMagenta : :: */[
  "45",
  /* :: */[
    "49",
    /* [] */0
  ]
];

var Styles_024 = /* bgCyan : :: */[
  "46",
  /* :: */[
    "49",
    /* [] */0
  ]
];

var Styles_025 = /* bgWhite : :: */[
  "47",
  /* :: */[
    "49",
    /* [] */0
  ]
];

var Styles_026 = /* bgBlackBright : :: */[
  "100",
  /* :: */[
    "49",
    /* [] */0
  ]
];

var Styles_027 = /* bgRedBright : :: */[
  "101",
  /* :: */[
    "49",
    /* [] */0
  ]
];

var Styles_028 = /* bgGreenBright : :: */[
  "102",
  /* :: */[
    "49",
    /* [] */0
  ]
];

var Styles_029 = /* bgYellowBright : :: */[
  "103",
  /* :: */[
    "49",
    /* [] */0
  ]
];

var Styles_030 = /* bgBlueBright : :: */[
  "104",
  /* :: */[
    "49",
    /* [] */0
  ]
];

var Styles_031 = /* bgMagentaBright : :: */[
  "105",
  /* :: */[
    "49",
    /* [] */0
  ]
];

var Styles_032 = /* bgCyanBright : :: */[
  "106",
  /* :: */[
    "49",
    /* [] */0
  ]
];

var Styles_033 = /* bgWhiteBright : :: */[
  "107",
  /* :: */[
    "49",
    /* [] */0
  ]
];

var Styles = /* module */[
  Styles_000,
  Styles_001,
  Styles_002,
  Styles_003,
  Styles_004,
  Styles_005,
  Styles_006,
  Styles_007,
  Styles_008,
  Styles_009,
  Styles_010,
  Styles_011,
  Styles_012,
  Styles_013,
  Styles_014,
  Styles_015,
  Styles_016,
  Styles_017,
  Styles_018,
  Styles_019,
  Styles_020,
  Styles_021,
  Styles_022,
  Styles_023,
  Styles_024,
  Styles_025,
  Styles_026,
  Styles_027,
  Styles_028,
  Styles_029,
  Styles_030,
  Styles_031,
  Styles_032,
  Styles_033
];

exports.Styles = Styles;
/* No side effect */
