// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


var reset = /* array */[
  "0",
  "0"
];

var bold = /* array */[
  "1",
  "22"
];

var dim = /* array */[
  "2",
  "22"
];

var italic = /* array */[
  "3",
  "23"
];

var underline = /* array */[
  "4",
  "24"
];

var inverse = /* array */[
  "7",
  "27"
];

var hidden = /* array */[
  "8",
  "28"
];

var strikethrough = /* array */[
  "9",
  "29"
];

var black = /* array */[
  "30",
  "39"
];

var red = /* array */[
  "31",
  "39"
];

var green = /* array */[
  "32",
  "39"
];

var yellow = /* array */[
  "33",
  "39"
];

var blue = /* array */[
  "34",
  "39"
];

var magenta = /* array */[
  "35",
  "39"
];

var cyan = /* array */[
  "36",
  "39"
];

var white = /* array */[
  "37",
  "39"
];

var gray = /* array */[
  "90",
  "39"
];

var grey = /* array */[
  "90",
  "39"
];

var bgBlack = /* array */[
  "40",
  "49"
];

var bgRed = /* array */[
  "41",
  "49"
];

var bgGreen = /* array */[
  "42",
  "49"
];

var bgYellow = /* array */[
  "43",
  "49"
];

var bgBlue = /* array */[
  "44",
  "49"
];

var bgMagenta = /* array */[
  "45",
  "49"
];

var bgCyan = /* array */[
  "46",
  "49"
];

var bgWhite = /* array */[
  "47",
  "49"
];

var Styles = /* module */[
  /* reset */reset,
  /* bold */bold,
  /* dim */dim,
  /* italic */italic,
  /* underline */underline,
  /* inverse */inverse,
  /* hidden */hidden,
  /* strikethrough */strikethrough,
  /* black */black,
  /* red */red,
  /* green */green,
  /* yellow */yellow,
  /* blue */blue,
  /* magenta */magenta,
  /* cyan */cyan,
  /* white */white,
  /* gray */gray,
  /* grey */grey,
  /* bgBlack */bgBlack,
  /* bgRed */bgRed,
  /* bgGreen */bgGreen,
  /* bgYellow */bgYellow,
  /* bgBlue */bgBlue,
  /* bgMagenta */bgMagenta,
  /* bgCyan */bgCyan,
  /* bgWhite */bgWhite
];

exports.Styles = Styles;
/* No side effect */
