// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry      = require("bs-platform/lib/js/curry.js");
var Styles     = require("./Styles.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");

function startWrap(v) {
  return "\u001b[" + (String(v) + "") + "m";
}

function endWrap(v) {
  return "\u001b[" + (String(v) + "") + "m";
}

function makeString(head, last, str) {
  return startWrap(head) + (str + endWrap(last));
}

function compose(f, g, x) {
  return Curry._1(f, Curry._1(g, x));
}

function pipe(f, g, x) {
  return Curry._1(g, Curry._1(f, x));
}

var partial_arg = Caml_array.caml_array_get(Styles.Styles[/* reset */0], 1);

var partial_arg$1 = Caml_array.caml_array_get(Styles.Styles[/* reset */0], 0);

function reset(param) {
  return makeString(partial_arg$1, partial_arg, param);
}

var partial_arg$2 = Caml_array.caml_array_get(Styles.Styles[/* bold */1], 1);

var partial_arg$3 = Caml_array.caml_array_get(Styles.Styles[/* bold */1], 0);

function bold(param) {
  return makeString(partial_arg$3, partial_arg$2, param);
}

var partial_arg$4 = Caml_array.caml_array_get(Styles.Styles[/* dim */2], 1);

var partial_arg$5 = Caml_array.caml_array_get(Styles.Styles[/* dim */2], 0);

function dim(param) {
  return makeString(partial_arg$5, partial_arg$4, param);
}

var partial_arg$6 = Caml_array.caml_array_get(Styles.Styles[/* italic */3], 1);

var partial_arg$7 = Caml_array.caml_array_get(Styles.Styles[/* italic */3], 0);

function italic(param) {
  return makeString(partial_arg$7, partial_arg$6, param);
}

var partial_arg$8 = Caml_array.caml_array_get(Styles.Styles[/* underline */4], 1);

var partial_arg$9 = Caml_array.caml_array_get(Styles.Styles[/* underline */4], 0);

function underline(param) {
  return makeString(partial_arg$9, partial_arg$8, param);
}

var partial_arg$10 = Caml_array.caml_array_get(Styles.Styles[/* inverse */5], 1);

var partial_arg$11 = Caml_array.caml_array_get(Styles.Styles[/* inverse */5], 0);

function inverse(param) {
  return makeString(partial_arg$11, partial_arg$10, param);
}

var partial_arg$12 = Caml_array.caml_array_get(Styles.Styles[/* hidden */6], 1);

var partial_arg$13 = Caml_array.caml_array_get(Styles.Styles[/* hidden */6], 0);

function hidden(param) {
  return makeString(partial_arg$13, partial_arg$12, param);
}

var partial_arg$14 = Caml_array.caml_array_get(Styles.Styles[/* strikethrough */7], 1);

var partial_arg$15 = Caml_array.caml_array_get(Styles.Styles[/* strikethrough */7], 0);

function strikethrough(param) {
  return makeString(partial_arg$15, partial_arg$14, param);
}

var partial_arg$16 = Caml_array.caml_array_get(Styles.Styles[/* black */8], 1);

var partial_arg$17 = Caml_array.caml_array_get(Styles.Styles[/* black */8], 0);

function black(param) {
  return makeString(partial_arg$17, partial_arg$16, param);
}

var partial_arg$18 = Caml_array.caml_array_get(Styles.Styles[/* red */9], 1);

var partial_arg$19 = Caml_array.caml_array_get(Styles.Styles[/* red */9], 0);

function red(param) {
  return makeString(partial_arg$19, partial_arg$18, param);
}

var partial_arg$20 = Caml_array.caml_array_get(Styles.Styles[/* green */10], 1);

var partial_arg$21 = Caml_array.caml_array_get(Styles.Styles[/* green */10], 0);

function green(param) {
  return makeString(partial_arg$21, partial_arg$20, param);
}

var partial_arg$22 = Caml_array.caml_array_get(Styles.Styles[/* yellow */11], 1);

var partial_arg$23 = Caml_array.caml_array_get(Styles.Styles[/* yellow */11], 0);

function yellow(param) {
  return makeString(partial_arg$23, partial_arg$22, param);
}

var partial_arg$24 = Caml_array.caml_array_get(Styles.Styles[/* blue */12], 1);

var partial_arg$25 = Caml_array.caml_array_get(Styles.Styles[/* blue */12], 0);

function blue(param) {
  return makeString(partial_arg$25, partial_arg$24, param);
}

var partial_arg$26 = Caml_array.caml_array_get(Styles.Styles[/* magenta */13], 1);

var partial_arg$27 = Caml_array.caml_array_get(Styles.Styles[/* magenta */13], 0);

function magenta(param) {
  return makeString(partial_arg$27, partial_arg$26, param);
}

var partial_arg$28 = Caml_array.caml_array_get(Styles.Styles[/* cyan */14], 1);

var partial_arg$29 = Caml_array.caml_array_get(Styles.Styles[/* cyan */14], 0);

function cyan(param) {
  return makeString(partial_arg$29, partial_arg$28, param);
}

var partial_arg$30 = Caml_array.caml_array_get(Styles.Styles[/* white */15], 1);

var partial_arg$31 = Caml_array.caml_array_get(Styles.Styles[/* white */15], 0);

function white(param) {
  return makeString(partial_arg$31, partial_arg$30, param);
}

var partial_arg$32 = Caml_array.caml_array_get(Styles.Styles[/* gray */16], 1);

var partial_arg$33 = Caml_array.caml_array_get(Styles.Styles[/* gray */16], 0);

function gray(param) {
  return makeString(partial_arg$33, partial_arg$32, param);
}

var partial_arg$34 = Caml_array.caml_array_get(Styles.Styles[/* grey */17], 1);

var partial_arg$35 = Caml_array.caml_array_get(Styles.Styles[/* grey */17], 0);

function grey(param) {
  return makeString(partial_arg$35, partial_arg$34, param);
}

var partial_arg$36 = Caml_array.caml_array_get(Styles.Styles[/* bgBlack */18], 1);

var partial_arg$37 = Caml_array.caml_array_get(Styles.Styles[/* bgBlack */18], 0);

function bgBlack(param) {
  return makeString(partial_arg$37, partial_arg$36, param);
}

var partial_arg$38 = Caml_array.caml_array_get(Styles.Styles[/* bgRed */19], 1);

var partial_arg$39 = Caml_array.caml_array_get(Styles.Styles[/* bgRed */19], 0);

function bgRed(param) {
  return makeString(partial_arg$39, partial_arg$38, param);
}

var partial_arg$40 = Caml_array.caml_array_get(Styles.Styles[/* bgGreen */20], 1);

var partial_arg$41 = Caml_array.caml_array_get(Styles.Styles[/* bgGreen */20], 0);

function bgGreen(param) {
  return makeString(partial_arg$41, partial_arg$40, param);
}

var partial_arg$42 = Caml_array.caml_array_get(Styles.Styles[/* bgYellow */21], 1);

var partial_arg$43 = Caml_array.caml_array_get(Styles.Styles[/* bgYellow */21], 0);

function bgYellow(param) {
  return makeString(partial_arg$43, partial_arg$42, param);
}

var partial_arg$44 = Caml_array.caml_array_get(Styles.Styles[/* bgBlue */22], 1);

var partial_arg$45 = Caml_array.caml_array_get(Styles.Styles[/* bgBlue */22], 0);

function bgBlue(param) {
  return makeString(partial_arg$45, partial_arg$44, param);
}

var partial_arg$46 = Caml_array.caml_array_get(Styles.Styles[/* bgMagenta */23], 1);

var partial_arg$47 = Caml_array.caml_array_get(Styles.Styles[/* bgMagenta */23], 0);

function bgMagenta(param) {
  return makeString(partial_arg$47, partial_arg$46, param);
}

var partial_arg$48 = Caml_array.caml_array_get(Styles.Styles[/* bgCyan */24], 1);

var partial_arg$49 = Caml_array.caml_array_get(Styles.Styles[/* bgCyan */24], 0);

function bgCyan(param) {
  return makeString(partial_arg$49, partial_arg$48, param);
}

var partial_arg$50 = Caml_array.caml_array_get(Styles.Styles[/* bgWhite */25], 1);

var partial_arg$51 = Caml_array.caml_array_get(Styles.Styles[/* bgWhite */25], 0);

function bgWhite(param) {
  return makeString(partial_arg$51, partial_arg$50, param);
}

var Utils = /* module */[
  /* compose */compose,
  /* pipe */pipe,
  /* reset */reset,
  /* bold */bold,
  /* dim */dim,
  /* italic */italic,
  /* underline */underline,
  /* inverse */inverse,
  /* hidden */hidden,
  /* strikethrough */strikethrough,
  /* black */black,
  /* red */red,
  /* green */green,
  /* yellow */yellow,
  /* blue */blue,
  /* magenta */magenta,
  /* cyan */cyan,
  /* white */white,
  /* gray */gray,
  /* grey */grey,
  /* bgBlack */bgBlack,
  /* bgRed */bgRed,
  /* bgGreen */bgGreen,
  /* bgYellow */bgYellow,
  /* bgBlue */bgBlue,
  /* bgMagenta */bgMagenta,
  /* bgCyan */bgCyan,
  /* bgWhite */bgWhite
];

exports.startWrap  = startWrap;
exports.endWrap    = endWrap;
exports.makeString = makeString;
exports.Utils      = Utils;
/* No side effect */
