// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry                   = require("bs-platform/lib/js/curry.js");
var Styles                  = require("./Styles.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function startWrap(v) {
  return "\u001b[" + (String(v) + "") + "m";
}

function endWrap(v) {
  return "\u001b[" + (String(v) + "") + "m";
}

function makeString(style, str) {
  var exit = 0;
  if (style) {
    var match = style[1];
    if (match) {
      if (match[1]) {
        exit = 1;
      } else {
        return startWrap(style[0]) + (str + endWrap(match[0]));
      }
    } else {
      exit = 1;
    }
  } else {
    exit = 1;
  }
  if (exit === 1) {
    throw [
          Caml_builtin_exceptions.match_failure,
          [
            "/Users/cabbio540/Sites/personal/re-color/src/Utils.re",
            8,
            6
          ]
        ];
  }
  
}

function compose(f, g, x) {
  return Curry._1(f, Curry._1(g, x));
}

function pipe(f, g, x) {
  return Curry._1(g, Curry._1(f, x));
}

var partial_arg = Styles.Styles[/* reset */0];

function reset(param) {
  return makeString(partial_arg, param);
}

var partial_arg$1 = Styles.Styles[/* bold */1];

function bold(param) {
  return makeString(partial_arg$1, param);
}

var partial_arg$2 = Styles.Styles[/* dim */2];

function dim(param) {
  return makeString(partial_arg$2, param);
}

var partial_arg$3 = Styles.Styles[/* italic */3];

function italic(param) {
  return makeString(partial_arg$3, param);
}

var partial_arg$4 = Styles.Styles[/* underline */4];

function underline(param) {
  return makeString(partial_arg$4, param);
}

var partial_arg$5 = Styles.Styles[/* inverse */5];

function inverse(param) {
  return makeString(partial_arg$5, param);
}

var partial_arg$6 = Styles.Styles[/* hidden */6];

function hidden(param) {
  return makeString(partial_arg$6, param);
}

var partial_arg$7 = Styles.Styles[/* strikethrough */7];

function strikethrough(param) {
  return makeString(partial_arg$7, param);
}

var partial_arg$8 = Styles.Styles[/* black */8];

function black(param) {
  return makeString(partial_arg$8, param);
}

var partial_arg$9 = Styles.Styles[/* red */9];

function red(param) {
  return makeString(partial_arg$9, param);
}

var partial_arg$10 = Styles.Styles[/* green */10];

function green(param) {
  return makeString(partial_arg$10, param);
}

var partial_arg$11 = Styles.Styles[/* yellow */11];

function yellow(param) {
  return makeString(partial_arg$11, param);
}

var partial_arg$12 = Styles.Styles[/* blue */12];

function blue(param) {
  return makeString(partial_arg$12, param);
}

var partial_arg$13 = Styles.Styles[/* magenta */13];

function magenta(param) {
  return makeString(partial_arg$13, param);
}

var partial_arg$14 = Styles.Styles[/* cyan */14];

function cyan(param) {
  return makeString(partial_arg$14, param);
}

var partial_arg$15 = Styles.Styles[/* white */15];

function white(param) {
  return makeString(partial_arg$15, param);
}

var partial_arg$16 = Styles.Styles[/* gray */16];

function gray(param) {
  return makeString(partial_arg$16, param);
}

var partial_arg$17 = Styles.Styles[/* grey */17];

function grey(param) {
  return makeString(partial_arg$17, param);
}

var partial_arg$18 = Styles.Styles[/* bgBlack */18];

function bgBlack(param) {
  return makeString(partial_arg$18, param);
}

var partial_arg$19 = Styles.Styles[/* bgRed */19];

function bgRed(param) {
  return makeString(partial_arg$19, param);
}

var partial_arg$20 = Styles.Styles[/* bgGreen */20];

function bgGreen(param) {
  return makeString(partial_arg$20, param);
}

var partial_arg$21 = Styles.Styles[/* bgYellow */21];

function bgYellow(param) {
  return makeString(partial_arg$21, param);
}

var partial_arg$22 = Styles.Styles[/* bgBlue */22];

function bgBlue(param) {
  return makeString(partial_arg$22, param);
}

var partial_arg$23 = Styles.Styles[/* bgMagenta */23];

function bgMagenta(param) {
  return makeString(partial_arg$23, param);
}

var partial_arg$24 = Styles.Styles[/* bgCyan */24];

function bgCyan(param) {
  return makeString(partial_arg$24, param);
}

var partial_arg$25 = Styles.Styles[/* bgWhite */25];

function bgWhite(param) {
  return makeString(partial_arg$25, param);
}

var partial_arg$26 = Styles.Styles[/* bgBlackBright */26];

function bgBlackBright(param) {
  return makeString(partial_arg$26, param);
}

var partial_arg$27 = Styles.Styles[/* bgRedBright */27];

function bgRedBright(param) {
  return makeString(partial_arg$27, param);
}

var partial_arg$28 = Styles.Styles[/* bgGreenBright */28];

function bgGreenBright(param) {
  return makeString(partial_arg$28, param);
}

var partial_arg$29 = Styles.Styles[/* bgYellowBright */29];

function bgYellowBright(param) {
  return makeString(partial_arg$29, param);
}

var partial_arg$30 = Styles.Styles[/* bgBlueBright */30];

function bgBlueBright(param) {
  return makeString(partial_arg$30, param);
}

var partial_arg$31 = Styles.Styles[/* bgMagentaBright */31];

function bgMagentaBright(param) {
  return makeString(partial_arg$31, param);
}

var partial_arg$32 = Styles.Styles[/* bgCyanBright */32];

function bgCyanBright(param) {
  return makeString(partial_arg$32, param);
}

var partial_arg$33 = Styles.Styles[/* bgWhiteBright */33];

function bgWhiteBright(param) {
  return makeString(partial_arg$33, param);
}

var Utils = /* module */[
  /* compose */compose,
  /* pipe */pipe,
  /* reset */reset,
  /* bold */bold,
  /* dim */dim,
  /* italic */italic,
  /* underline */underline,
  /* inverse */inverse,
  /* hidden */hidden,
  /* strikethrough */strikethrough,
  /* black */black,
  /* red */red,
  /* green */green,
  /* yellow */yellow,
  /* blue */blue,
  /* magenta */magenta,
  /* cyan */cyan,
  /* white */white,
  /* gray */gray,
  /* grey */grey,
  /* bgBlack */bgBlack,
  /* bgRed */bgRed,
  /* bgGreen */bgGreen,
  /* bgYellow */bgYellow,
  /* bgBlue */bgBlue,
  /* bgMagenta */bgMagenta,
  /* bgCyan */bgCyan,
  /* bgWhite */bgWhite,
  /* bgBlackBright */bgBlackBright,
  /* bgRedBright */bgRedBright,
  /* bgGreenBright */bgGreenBright,
  /* bgYellowBright */bgYellowBright,
  /* bgBlueBright */bgBlueBright,
  /* bgMagentaBright */bgMagentaBright,
  /* bgCyanBright */bgCyanBright,
  /* bgWhiteBright */bgWhiteBright
];

exports.startWrap  = startWrap;
exports.endWrap    = endWrap;
exports.makeString = makeString;
exports.Utils      = Utils;
/* No side effect */
